import './globals.css'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'] })

export const metadata = {
  title: 'Image Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
